name: Build Payment Channel Plugins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Alipay Plugin (Linux) - All Versions
      run: |
        cd examples/alipay_channel
        
        echo "=== Building Full Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4" -trimpath -o alipay_channel_linux.so alipay_channel.go
        echo "Full version size:"
        ls -la alipay_channel_linux.so
        
        echo "=== Building Minimal Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_minimal_linux.so alipay_channel_minimal.go
        echo "Minimal version size:"
        ls -la alipay_channel_minimal_linux.so
        
        echo "=== Building Ultra-Minimal Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_ultra_minimal_linux.so alipay_channel_ultra_minimal.go
        echo "Ultra-minimal version size:"
        ls -la alipay_channel_ultra_minimal_linux.so
        
        echo "=== Building Ultra-Stripped Version ==="
        go build -buildmode=plugin -ldflags="-s -w -H linux -E" -gcflags="-l=4 -B -N -shared" -trimpath -a -installsuffix stripped -o alipay_channel_ultra_stripped_linux.so alipay_channel_ultra_stripped.go
        echo "Ultra-stripped version size:"
        ls -la alipay_channel_ultra_stripped_linux.so
        
        echo "=== Building Absolute Minimal Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_absolute_minimal_linux.so alipay_channel_absolute_minimal.go
        echo "Absolute minimal version size:"
        ls -la alipay_channel_absolute_minimal_linux.so
        
        echo "=== Size Comparison ==="
        echo "Full: $(du -h alipay_channel_linux.so | cut -f1)"
        echo "Minimal: $(du -h alipay_channel_minimal_linux.so | cut -f1)"
        echo "Ultra-Minimal: $(du -h alipay_channel_ultra_minimal_linux.so | cut -f1)"
        echo "Ultra-Stripped: $(du -h alipay_channel_ultra_stripped_linux.so | cut -f1)"
        echo "Absolute-Minimal: $(du -h alipay_channel_absolute_minimal_linux.so | cut -f1)"
    
    - name: Upload Linux Plugins
      uses: actions/upload-artifact@v4
      with:
        name: alipay-channel-linux
        path: examples/alipay_channel/alipay_channel_*.so

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Alipay Plugin (macOS) - All Versions
      run: |
        cd examples/alipay_channel
        
        echo "=== Building Full Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4" -trimpath -o alipay_channel_darwin.so alipay_channel.go
        echo "Full version size:"
        ls -la alipay_channel_darwin.so
        
        echo "=== Building Minimal Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_minimal_darwin.so alipay_channel_minimal.go
        echo "Minimal version size:"
        ls -la alipay_channel_minimal_darwin.so
        
        echo "=== Building Ultra-Minimal Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_ultra_minimal_darwin.so alipay_channel_ultra_minimal.go
        echo "Ultra-minimal version size:"
        ls -la alipay_channel_ultra_minimal_darwin.so
        
        echo "=== Building Ultra-Stripped Version ==="
        go build -buildmode=plugin -ldflags="-s -w -H darwin -E" -gcflags="-l=4 -B -N -shared" -trimpath -a -installsuffix stripped -o alipay_channel_ultra_stripped_darwin.so alipay_channel_ultra_stripped.go
        echo "Ultra-stripped version size:"
        ls -la alipay_channel_ultra_stripped_darwin.so
        
        echo "=== Building Absolute Minimal Version ==="
        go build -buildmode=plugin -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_absolute_minimal_darwin.so alipay_channel_absolute_minimal.go
        echo "Absolute minimal version size:"
        ls -la alipay_channel_absolute_minimal_darwin.so
        
        echo "=== Size Comparison ==="
        echo "Full: $(du -h alipay_channel_darwin.so | cut -f1)"
        echo "Minimal: $(du -h alipay_channel_minimal_darwin.so | cut -f1)"
        echo "Ultra-Minimal: $(du -h alipay_channel_ultra_minimal_darwin.so | cut -f1)"
        echo "Ultra-Stripped: $(du -h alipay_channel_ultra_stripped_darwin.so | cut -f1)"
        echo "Absolute-Minimal: $(du -h alipay_channel_absolute_minimal_darwin.so | cut -f1)"
    
    - name: Upload macOS Plugins
      uses: actions/upload-artifact@v4
      with:
        name: alipay-channel-macos
        path: examples/alipay_channel/alipay_channel_*.so

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Windows Executables - All Versions
      run: |
        cd examples/alipay_channel
        
        echo "=== Building Full Version ==="
        go build -ldflags="-s -w" -gcflags="-l=4" -trimpath -o alipay_channel_windows.exe alipay_channel.go
        echo "Full version size:"
        ls -la alipay_channel_windows.exe
        
        echo "=== Building Minimal Version ==="
        go build -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_minimal_windows.exe alipay_channel_minimal.go
        echo "Minimal version size:"
        ls -la alipay_channel_minimal_windows.exe
        
        echo "=== Building Ultra-Minimal Version ==="
        go build -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_ultra_minimal_windows.exe alipay_channel_ultra_minimal.go
        echo "Ultra-minimal version size:"
        ls -la alipay_channel_ultra_minimal_windows.exe
        
        echo "=== Building Ultra-Stripped Version ==="
        go build -ldflags="-s -w -H windows -E" -gcflags="-l=4 -B -N -shared" -trimpath -a -installsuffix stripped -o alipay_channel_ultra_stripped_windows.exe alipay_channel_ultra_stripped.go
        echo "Ultra-stripped version size:"
        ls -la alipay_channel_ultra_stripped_windows.exe
        
        echo "=== Building Absolute Minimal Version ==="
        go build -ldflags="-s -w" -gcflags="-l=4 -B -N" -trimpath -o alipay_channel_absolute_minimal_windows.exe alipay_channel_absolute_minimal.go
        echo "Absolute minimal version size:"
        ls -la alipay_channel_absolute_minimal_windows.exe
        
        echo "=== Size Comparison ==="
        echo "Full: $(Get-ChildItem alipay_channel_windows.exe | ForEach-Object { [math]::Round($_.Length/1MB, 2) }) MB"
        echo "Minimal: $(Get-ChildItem alipay_channel_minimal_windows.exe | ForEach-Object { [math]::Round($_.Length/1MB, 2) }) MB"
        echo "Ultra-Minimal: $(Get-ChildItem alipay_channel_ultra_minimal_windows.exe | ForEach-Object { [math]::Round($_.Length/1MB, 2) }) MB"
        echo "Ultra-Stripped: $(Get-ChildItem alipay_channel_ultra_stripped_windows.exe | ForEach-Object { [math]::Round($_.Length/1MB, 2) }) MB"
        echo "Absolute-Minimal: $(Get-ChildItem alipay_channel_absolute_minimal_windows.exe | ForEach-Object { [math]::Round($_.Length/1MB, 2) }) MB"
    
    - name: Upload Windows Executables
      uses: actions/upload-artifact@v4
      with:
        name: alipay-channel-windows
        path: examples/alipay_channel/alipay_channel_*.exe
